#!/bin/bash

# Dotfiles Setup Script
# This script creates symlinks from the dotfiles directory to the correct config locations
# For installing dependencies, use ./install.sh
# Supports macOS, Linux, and WSL.

set -e # Exit on error

# ============================================================================
# OS Detection
# ============================================================================
detect_os() {
    case "$(uname -s)" in
        Darwin) echo "macos" ;;
        Linux)
            if grep -qi microsoft /proc/version 2>/dev/null || [ -n "$WSL_DISTRO_NAME" ]; then
                echo "wsl"
            else
                echo "linux"
            fi
            ;;
        *) echo "unsupported" ;;
    esac
}

OS="$(detect_os)"

# ============================================================================
# User Configuration File
# ============================================================================
# Saved preferences live in ~/.config/dotfiles/config (one per host).
# Each entry is COMPONENT_<NAME>=<local|windows|skip>.
DOTFILES_CONF_DIR="$HOME/.config/dotfiles"
DOTFILES_CONF_FILE="$DOTFILES_CONF_DIR/config"

load_config() {
    [ -f "$DOTFILES_CONF_FILE" ] || return 1
    # shellcheck disable=SC1090
    source "$DOTFILES_CONF_FILE"
    return 0
}

save_config() {
    mkdir -p "$DOTFILES_CONF_DIR"
    {
        echo "# Dotfiles setup preferences (generated by setup.sh)"
        echo "# Re-run with --reconfigure to change."
        echo "OS_AT_SETUP=\"$OS\""
        echo "WIN_HOME=\"$WIN_HOME\""
        echo "COMPONENT_WEZTERM=\"$COMPONENT_WEZTERM\""
        echo "COMPONENT_KITTY=\"$COMPONENT_KITTY\""
        echo "COMPONENT_GHOSTTY=\"$COMPONENT_GHOSTTY\""
        echo "COMPONENT_TMUX=\"$COMPONENT_TMUX\""
        echo "COMPONENT_NVIM=\"$COMPONENT_NVIM\""
        echo "COMPONENT_STARSHIP=\"$COMPONENT_STARSHIP\""
        echo "COMPONENT_ZSH=\"$COMPONENT_ZSH\""
    } > "$DOTFILES_CONF_FILE"
}

# ============================================================================
# WSL: Detect Windows %USERPROFILE% mounted under /mnt/c
# ============================================================================
detect_windows_home() {
    [ "$OS" = "wsl" ] || { echo ""; return 0; }

    # Try cmd.exe first (most reliable on modern WSL).
    local win_userprofile
    win_userprofile="$(cmd.exe /c 'echo %USERPROFILE%' 2>/dev/null | tr -d '\r')"

    if [ -n "$win_userprofile" ] && command -v wslpath &>/dev/null; then
        wslpath "$win_userprofile" 2>/dev/null
        return 0
    fi

    # Fallback: scan /mnt/c/Users for a single non-system user dir.
    if [ -d /mnt/c/Users ]; then
        local candidate
        candidate=$(find /mnt/c/Users -mindepth 1 -maxdepth 1 -type d \
            ! -name 'Public' ! -name 'Default*' ! -name 'All Users' \
            ! -name 'desktop.ini' 2>/dev/null | head -1)
        [ -n "$candidate" ] && echo "$candidate" && return 0
    fi

    echo ""
}

# Convert "local"/"windows" into the actual home directory for a component.
target_home_for() {
    case "$1" in
        local)   echo "$HOME" ;;
        windows) echo "$WIN_HOME" ;;
        *)       echo "" ;;
    esac
}

# ============================================================================
# Colors and Formatting
# ============================================================================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

CHECK="✓"
CROSS="✗"
ARROW="→"
WARN="⚠"
INFO="ℹ"

print_header() {
    echo ""
    echo -e "${BOLD}${MAGENTA}$1${NC}"
    echo -e "${MAGENTA}$(printf '=%.0s' {1..50})${NC}"
}

print_success() { echo -e "${GREEN}${CHECK}${NC} $1"; }
print_error() { echo -e "${RED}${CROSS}${NC} $1"; }
print_warning() { echo -e "${YELLOW}${WARN}${NC} $1"; }
print_info() { echo -e "${CYAN}${INFO}${NC} $1"; }
print_step() { echo -e "${BLUE}${ARROW}${NC} $1"; }

# ============================================================================
# Configuration
# ============================================================================
DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_DIR="$HOME/.dotfiles_backup/$(date +%Y%m%d_%H%M%S)"
DRY_RUN=false
BACKUP=true
RECONFIGURE=false
WIN_HOME=""

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run | -n)
            DRY_RUN=true
            shift
            ;;
        --no-backup)
            BACKUP=false
            shift
            ;;
        --reconfigure)
            RECONFIGURE=true
            shift
            ;;
        --help | -h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --dry-run, -n    Show what would be done without making changes"
            echo "  --no-backup      Don't backup existing files"
            echo "  --reconfigure    Re-prompt for component preferences and overwrite saved config"
            echo "  --help, -h       Show this help message"
            echo ""
            echo "On first run (or with --reconfigure), setup prompts for which components"
            echo "to install and (on WSL) whether to link them to WSL home or Windows home."
            echo "Choices are saved to ~/.config/dotfiles/config for subsequent runs."
            echo ""
            echo "Examples:"
            echo "  $0                # Setup symlinks (interactive on first run)"
            echo "  $0 --dry-run      # Preview changes"
            echo "  $0 --reconfigure  # Re-pick which components to install"
            echo ""
            echo "For installing dependencies, use: ./install.sh"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# ============================================================================
# Symlink Function
# ============================================================================
create_symlink() {
    local source="$1"
    local target="$2"

    if [ "$DRY_RUN" = true ]; then
        print_step "[DRY RUN] Would link: $target ${ARROW} $source"
        return
    fi

    # Backup existing file/directory
    if [ -e "$target" ] || [ -L "$target" ]; then
        if [ "$BACKUP" = true ]; then
            mkdir -p "$BACKUP_DIR"
            print_step "Backing up: $target"
            mv "$target" "$BACKUP_DIR/"
        else
            print_step "Removing: $target"
            rm -rf "$target"
        fi
    fi

    # Create parent directory if needed
    mkdir -p "$(dirname "$target")"

    # Create symlink
    ln -s "$source" "$target"
    print_success "Linked: $(basename "$target")"
}

# ============================================================================
# Quick Dependency Check
# ============================================================================
check_essentials() {
    print_header "Checking Essentials"

    local missing=()
    local tools=("git" "nvim" "zsh")

    for tool in "${tools[@]}"; do
        if command -v "$tool" &> /dev/null; then
            print_success "$tool"
        else
            print_error "$tool (missing)"
            missing+=("$tool")
        fi
    done

    if [ ${#missing[@]} -gt 0 ]; then
        echo ""
        print_warning "Missing tools detected!"
        print_info "Run ./install.sh first to install dependencies"
    fi
}

# ============================================================================
# Interactive Component Prompt
# ============================================================================
# Asks the user once per component. Defaults adapt to detected OS:
#   - macOS/Linux components get "local" by default (Y/n style).
#   - On WSL, GUI components (WezTerm) default to "windows"; CLI components
#     (tmux, zsh, nvim, starship) default to "local" (the WSL home).
# Accepted answers (case-insensitive): l/local, w/windows, s/skip, plus
# y (= default), n (= skip), and empty (= default).
prompt_choice() {
    # $1 = label, $2 = default (local|windows|skip), $3 = allow_windows (true|false)
    local label="$1" default="$2" allow_win="$3"
    local opts choice

    if [ "$allow_win" = "true" ]; then
        opts="[l]ocal / [w]indows / [s]kip"
    else
        opts="[l]ocal / [s]kip"
    fi

    while true; do
        printf "  %-12s %s (default: %s): " "$label" "$opts" "$default" >&2
        read -r choice
        choice=$(printf '%s' "$choice" | tr '[:upper:]' '[:lower:]')
        case "$choice" in
            "")           echo "$default"; return ;;
            l|local)      echo "local"; return ;;
            w|windows)
                if [ "$allow_win" = "true" ]; then echo "windows"; return; fi
                echo "    (windows not applicable here)" >&2
                ;;
            s|skip|n|no)  echo "skip"; return ;;
            y|yes)        echo "$default"; return ;;
            *)            echo "    (please enter l, w, s, or press Enter)" >&2 ;;
        esac
    done
}

prompt_components() {
    print_header "Component Preferences"
    print_info "Pick a target for each component. Press Enter to accept the default."
    if [ "$OS" = "wsl" ]; then
        if [ -n "$WIN_HOME" ]; then
            print_info "Windows home: $WIN_HOME"
        else
            print_warning "Could not detect Windows home — 'windows' targets will be disabled."
        fi
    fi
    echo ""

    local allow_win="false"
    [ "$OS" = "wsl" ] && [ -n "$WIN_HOME" ] && allow_win="true"

    # WezTerm — GUI; default to "windows" on WSL, "local" elsewhere.
    local wt_default="local"
    [ "$OS" = "wsl" ] && [ -n "$WIN_HOME" ] && wt_default="windows"
    COMPONENT_WEZTERM=$(prompt_choice "WezTerm"  "$wt_default" "$allow_win")

    # Kitty — no real Windows version; on WSL default to skip.
    local kt_default="local"
    [ "$OS" = "wsl" ] && kt_default="skip"
    COMPONENT_KITTY=$(prompt_choice "Kitty"    "$kt_default" "false")

    # Ghostty — Windows support is preview-only; on WSL default to skip.
    local gh_default="local"
    [ "$OS" = "wsl" ] && gh_default="skip"
    COMPONENT_GHOSTTY=$(prompt_choice "Ghostty"  "$gh_default" "false")

    # CLI components — always local-or-skip.
    COMPONENT_TMUX=$(prompt_choice     "Tmux"     "local" "false")
    COMPONENT_NVIM=$(prompt_choice     "Neovim"   "local" "$allow_win")
    COMPONENT_STARSHIP=$(prompt_choice "Starship" "local" "$allow_win")
    COMPONENT_ZSH=$(prompt_choice      "Zsh"      "local" "false")
}

# ============================================================================
# Main Setup
# ============================================================================
main() {
    echo ""
    echo -e "${BOLD}${CYAN}╔════════════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${CYAN}║          Dotfiles Setup                            ║${NC}"
    echo -e "${BOLD}${CYAN}╚════════════════════════════════════════════════════╝${NC}"
    echo ""
    print_info "Dotfiles: $DOTFILES_DIR"
    print_info "Detected OS: $OS"

    if [ "$OS" = "unsupported" ]; then
        print_error "Unsupported OS. This script supports macOS, Linux, and WSL."
        exit 1
    fi

    if [ "$DRY_RUN" = true ]; then
        print_warning "DRY RUN MODE - No changes will be made"
    fi

    if [ "$BACKUP" = true ] && [ "$DRY_RUN" = false ]; then
        print_info "Backups: $BACKUP_DIR"
    fi

    # Load saved preferences or prompt (interactive on first run / --reconfigure)
    if [ "$RECONFIGURE" = true ] || ! load_config; then
        WIN_HOME=$(detect_windows_home)
        prompt_components
        if [ "$DRY_RUN" = false ]; then
            save_config
            print_success "Saved preferences to $DOTFILES_CONF_FILE"
        else
            print_step "[DRY RUN] Would save preferences to $DOTFILES_CONF_FILE"
        fi
    else
        print_info "Loaded preferences from $DOTFILES_CONF_FILE (use --reconfigure to change)"
    fi

    # Quick check
    check_essentials

    # WezTerm — target picked by COMPONENT_WEZTERM (local/windows/skip).
    # On Windows, WezTerm reads ~/.wezterm.lua from %USERPROFILE%, so the
    # filename is the same on both sides.
    print_header "WezTerm ($COMPONENT_WEZTERM)"
    if [ "$COMPONENT_WEZTERM" = "skip" ]; then
        print_info "Skipped (per saved preference)"
    else
        local wt_home
        wt_home="$(target_home_for "$COMPONENT_WEZTERM")"
        if [ -z "$wt_home" ]; then
            print_warning "No target home for WezTerm ($COMPONENT_WEZTERM) — skipping"
        else
            create_symlink "$DOTFILES_DIR/wezterm/.wezterm.lua" "$wt_home/.wezterm.lua"
            [ -f "$DOTFILES_DIR/wezterm/config.lua" ] &&
                create_symlink "$DOTFILES_DIR/wezterm/config.lua" "$wt_home/config.lua"
            [ -f "$DOTFILES_DIR/wezterm/events.lua" ] &&
                create_symlink "$DOTFILES_DIR/wezterm/events.lua" "$wt_home/events.lua"
        fi
    fi

    # Tmux — local only (no Windows tmux).
    print_header "Tmux ($COMPONENT_TMUX)"
    if [ "$COMPONENT_TMUX" = "skip" ]; then
        print_info "Skipped (per saved preference)"
    elif [ -f "$DOTFILES_DIR/tmux/tmux.conf" ]; then
        create_symlink "$DOTFILES_DIR/tmux/tmux.conf" "$HOME/.tmux.conf"
    else
        print_info "Skipped (no config found)"
    fi

    # Kitty — local only (no real Windows Kitty).
    print_header "Kitty ($COMPONENT_KITTY)"
    if [ "$COMPONENT_KITTY" = "skip" ]; then
        print_info "Skipped (per saved preference)"
    elif [ -d "$DOTFILES_DIR/kitty" ]; then
        create_symlink "$DOTFILES_DIR/kitty" "$HOME/.config/kitty"
    else
        print_info "Skipped (not found)"
    fi

    # Ghostty — local only (Windows support is preview/unstable).
    print_header "Ghostty ($COMPONENT_GHOSTTY)"
    if [ "$COMPONENT_GHOSTTY" = "skip" ]; then
        print_info "Skipped (per saved preference)"
    elif [ -f "$DOTFILES_DIR/ghostty/config" ]; then
        create_symlink "$DOTFILES_DIR/ghostty/config" "$HOME/.config/ghostty/config"
    else
        print_info "Skipped (not found)"
    fi

    # Regenerate Ghostty colors only if Ghostty was actually linked locally.
    if [ "$COMPONENT_GHOSTTY" != "local" ]; then
        print_step "Skipping ghostty/colors.inc regeneration (Ghostty not local)"
    elif [ "$DRY_RUN" = true ]; then
        print_step "[DRY RUN] Would regenerate ghostty/colors.inc"
    else
        print_step "Regenerating ghostty/colors.inc..."
        if source "$HOME/.config/zsh/.zshenv" 2> /dev/null; then
            if source "$HOME/.config/zsh/colors.zsh" 2> /dev/null; then
                _generate_ghostty_config && print_success "colors.inc regenerated (theme: $THEME)" ||
                    print_warning "Failed to generate colors.inc"
            else
                print_warning "colors.zsh not found"
            fi
        else
            print_warning "Could not source .zshenv"
        fi
    fi

    # Neovim — local: ~/.config/nvim; windows (WSL): %LOCALAPPDATA%/nvim
    print_header "Neovim ($COMPONENT_NVIM)"
    case "$COMPONENT_NVIM" in
        skip)    print_info "Skipped (per saved preference)" ;;
        local)   create_symlink "$DOTFILES_DIR/nvim" "$HOME/.config/nvim" ;;
        windows)
            if [ -n "$WIN_HOME" ]; then
                create_symlink "$DOTFILES_DIR/nvim" "$WIN_HOME/AppData/Local/nvim"
            else
                print_warning "Windows home unknown — skipping Neovim windows link"
            fi
            ;;
    esac

    # Starship — local: ~/.config/starship.toml; windows: same path under Windows home.
    print_header "Starship ($COMPONENT_STARSHIP)"
    if [ "$COMPONENT_STARSHIP" = "skip" ]; then
        print_info "Skipped (per saved preference)"
    elif [ -f "$DOTFILES_DIR/starship/starship.toml" ]; then
        local ss_home
        ss_home="$(target_home_for "$COMPONENT_STARSHIP")"
        if [ -n "$ss_home" ]; then
            create_symlink "$DOTFILES_DIR/starship/starship.toml" "$ss_home/.config/starship.toml"
        else
            print_warning "No target home for Starship ($COMPONENT_STARSHIP) — skipping"
        fi
    else
        print_info "Skipped (not found)"
    fi

    # Zsh — local only (zsh doesn't run on native Windows).
    print_header "Zsh ($COMPONENT_ZSH)"
    if [ "$COMPONENT_ZSH" = "skip" ]; then
        print_info "Skipped (per saved preference)"
    else
        create_symlink "$DOTFILES_DIR/zsh" "$HOME/.config/zsh"
    fi

    # Download git-completion.bash if missing (required by custom.zsh)
    GIT_COMPLETION="$DOTFILES_DIR/zsh/git-completion.bash"
    if [ ! -f "$GIT_COMPLETION" ]; then
        if [ "$DRY_RUN" = true ]; then
            print_step "[DRY RUN] Would download git-completion.bash"
        else
            print_step "Downloading git-completion.bash..."
            curl -fsSo "$GIT_COMPLETION" \
                https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash &&
                print_success "git-completion.bash downloaded" ||
                print_warning "Failed to download git-completion.bash"
        fi
    else
        print_success "git-completion.bash (already present)"
    fi

    # Setup shell config files (APPEND only, never overwrite existing content)
    print_header "Shell Configuration"
    if [ "$COMPONENT_ZSH" = "skip" ]; then
        print_info "Skipped (zsh component disabled)"
    elif [ "$DRY_RUN" = false ]; then
        # ~/.zshenv - sources our environment variables
        ZSHENV_LINE='[ -f "$HOME/.config/zsh/.zshenv" ] && source "$HOME/.config/zsh/.zshenv"'
        if [ ! -f "$HOME/.zshenv" ]; then
            # File doesn't exist, create it
            echo "# Dotfiles environment" > "$HOME/.zshenv"
            echo "$ZSHENV_LINE" >> "$HOME/.zshenv"
            print_success "Created ~/.zshenv"
        elif ! grep -q ".config/zsh/.zshenv" "$HOME/.zshenv" 2> /dev/null; then
            # File exists but doesn't have our line, APPEND (don't overwrite)
            echo "" >> "$HOME/.zshenv"
            echo "# Dotfiles environment" >> "$HOME/.zshenv"
            echo "$ZSHENV_LINE" >> "$HOME/.zshenv"
            print_success "Appended to ~/.zshenv"
        else
            print_info "~/.zshenv already configured"
        fi

        # ~/.zshrc - sources our shell config
        ZSHRC_LINE='[ -f "$HOME/.config/zsh/.zshrc" ] && source "$HOME/.config/zsh/.zshrc"'
        if [ ! -f "$HOME/.zshrc" ]; then
            # File doesn't exist, create it
            echo "# Dotfiles shell config" > "$HOME/.zshrc"
            echo "$ZSHRC_LINE" >> "$HOME/.zshrc"
            print_success "Created ~/.zshrc"
        elif ! grep -q ".config/zsh/.zshrc" "$HOME/.zshrc" 2> /dev/null; then
            # File exists but doesn't have our line, APPEND (don't overwrite)
            echo "" >> "$HOME/.zshrc"
            echo "# Dotfiles shell config" >> "$HOME/.zshrc"
            echo "$ZSHRC_LINE" >> "$HOME/.zshrc"
            print_success "Appended to ~/.zshrc"
        else
            print_info "~/.zshrc already configured"
        fi
    else
        print_step "[DRY RUN] Would append to ~/.zshenv and ~/.zshrc (never overwrites)"
    fi

    # Verification — only check what we tried to link.
    print_header "Verification"
    local files=()
    [ "$COMPONENT_ZSH" != "skip" ]  && files+=("$HOME/.config/zsh/.zshrc:Zsh")
    case "$COMPONENT_NVIM" in
        local)   files+=("$HOME/.config/nvim/init.lua:Neovim") ;;
        windows) [ -n "$WIN_HOME" ] && files+=("$WIN_HOME/AppData/Local/nvim/init.lua:Neovim (Windows)") ;;
    esac
    case "$COMPONENT_WEZTERM" in
        local)   files+=("$HOME/.wezterm.lua:WezTerm") ;;
        windows) [ -n "$WIN_HOME" ] && files+=("$WIN_HOME/.wezterm.lua:WezTerm (Windows)") ;;
    esac
    [ "$COMPONENT_GHOSTTY" = "local" ] && files+=("$HOME/.config/ghostty/config:Ghostty")

    for item in "${files[@]}"; do
        local file="${item%:*}"
        local name="${item#*:}"
        if [ -e "$file" ] || [ -L "$file" ]; then
            print_success "$name"
        else
            print_error "$name"
        fi
    done

    # Summary
    print_header "Complete!"

    if [ "$DRY_RUN" = true ]; then
        print_warning "Dry run - no changes made"
        print_info "Run without --dry-run to apply"
    else
        print_success "All configurations linked!"
        [ -d "$BACKUP_DIR" ] && print_info "Backups: $BACKUP_DIR"

        # Auto-reload everything (macOS-only — `open -a`/`killall` are mac-specific
        # and the WSL/Linux flows don't manage these GUI apps).
        if [ "$OS" = "macos" ]; then
            print_header "Reloading..."

            # Reload WezTerm if running
            if command -v wezterm &> /dev/null && pgrep -f "wezterm" &> /dev/null; then
                wezterm cli reload-configuration 2> /dev/null &&
                    print_success "WezTerm reloaded" ||
                    print_info "WezTerm: restart manually"
            fi

            # Reload Starship (just needs shell reload)
            if command -v starship &> /dev/null; then
                print_success "Starship will reload with shell"
            fi

            # Reload Ghostty if running
            if command -v ghostty &> /dev/null && pgrep -x ghostty &> /dev/null; then
                print_info "Reloading Ghostty..."
                killall ghostty 2> /dev/null
                sleep 0.1
                open -a ghostty 2> /dev/null && print_success "Ghostty reloaded" ||
                    print_info "Ghostty: restart manually"
            fi
        else
            print_info "Reload your terminal manually to pick up changes."
        fi

        # Source the new shell config
        print_info "Sourcing shell configuration..."

        echo ""
        echo -e "${BOLD}${GREEN}✓ Setup complete!${NC}"
        echo ""
        echo -e "  ${CYAN}Themes:${NC} anysphere, catppuccin, nord, nordic, onedark"
        echo ""
        echo -e "${YELLOW}${WARN}${NC} ${BOLD}Run this to apply shell changes:${NC}"
        echo -e "    ${CYAN}source ~/.zshrc${NC}"
        echo ""
    fi
}

main
