"$schema" = 'https://starship.rs/config-schema.json'

format = """
 $os\
[]() \
$username\
[|](bright-black) \
$directory\
$git_branch\
$git_status\
$fill\
$python \
$time\
$line_break\
$character"""
[fill]
symbol = " "
style = "black"


[os]
disabled = false
style = "cyan"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "cyan"
style_root = "cyan bold"
format = '[$user ]($style)'

[directory]
style = "blue"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = ""
style = "purple"
format = '[|](bright-black) [$symbol $branch ]($style)'

[git_status]
style = "purple"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "blue"
format = '[$symbol( $version) ]($style)'

[c]
symbol = " "
style = "blue"
format = '[$symbol( $version) ]($style)'

[cpp]
symbol = " "
style = "blue"
format = '[$symbol( $version) ]($style)'

[rust]
symbol = ""
style = "blue"
format = '[$symbol( $version) ]($style)'

[golang]
symbol = ""
style = "blue"
format = '[$symbol( $version) ]($style)'

[php]
symbol = ""
style = "blue"
format = '[$symbol( $version) ]($style)'

[java]
symbol = ""
style = "blue"
format = '[$symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "blue"
format = '[$symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "blue"
format = '[$symbol( $version) ]($style)'

[python]
symbol = ""
style = "yellow"
format = '[$symbol $virtualenv ](yellow)'

[docker_context]
symbol = ""
style = "dimmed bright-black"
format = '[$symbol( $context) ]($style)'

[conda]
symbol = ""
style = "dimmed bright-black"
format = '[$symbol( $environment) ]($style)'

[pixi]
symbol = "P "
style = "dimmed bright-black"
format = '[$symbol( $version)( $environment) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bright-black"
format = '[$time]($style) '

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ >](green)'
error_symbol = '[ >](red)'
vimcmd_symbol = '[ <](green)'
vimcmd_replace_one_symbol = '[ <](purple)'
vimcmd_replace_symbol = '[ <](purple)'
vimcmd_visual_symbol = '[ <](yellow)'
