# Prefix and key table
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Terminal / colors
set -g default-terminal "${TERM}"
set-option -g terminal-overrides ',xterm-255color:RGB'

# General options
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 1             # zero-out escape time delay
set -g history-limit 10000       # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g focus-events on
set-hook -g pane-focus-out 'select-pane -P bg=colour=#141414,fg=colour10'
set-hook -g pane-focus-in 'select-pane -P bg=default,fg=default'
set -g pane-active-border-style 'fg=green,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'
set -g mouse on # Enable mouse interactions

# Session / server quit behavior (mac-style)
# Close this client only (like ⌘W)
unbind w
bind w detach-client        # uppercase W

# Quit session with confirmation
unbind q
bind q confirm-before -p "Kill tmux session '#S'? (y/n)" kill-session

unbind v
bind v copy-mode

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane resizing with arrows
bind -r Left resize-pane -L 5
bind -r Right resize-pane -R 5
bind -r Down resize-pane -D 5
bind -r Up resize-pane -U 5

# Splits and popups
bind-key g split-window -h -p 35 -c "#{pane_current_path}" "opencode"   # opencode 35% right
bind-key t split-window -v -p 30 -c "#{pane_current_path}"            # terminal 30% bottom

unbind %
bind-key | split-window -h -c "#{pane_current_path}"   # vertical split

unbind '"'
bind-key - split-window -v -c "#{pane_current_path}"   # horizontal split

# reload config
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"


# Plugins (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# statusbar
set -g status-position bottom
set -g status-style 'fg=white'
set -g status-justify centre
setw -g window-status-format ' #I:#W '
setw -g window-status-current-style 'fg=brightwhite bg=black'
setw -g window-status-current-format ' #I:#W '
set -g window-status-separator '#[fg=black]|'
set -g status-left ''
set -g status-left-style 'fg=green bg=brightblack'

set -g status-right ''
set -g status-right-style 'fg=green bg=brightblack'

setw -g window-status-bell-style 'fg=white bg=brightblack'

# messages
set -g message-style 'fg=white bg=black'

run '~/.tmux/plugins/tpm/tpm'
