# Unified Color System
# All theme colors are defined here and exported as environment variables
# Sourced by .zshenv

# Mellifluous Theme Colors (default)
export COLOR_FG="#cccccc"
export COLOR_BG="#141414"
export COLOR_CURSOR="#cccccc"
export COLOR_SELECTION_FG="#cccccc"
export COLOR_SELECTION_BG="#2d2d2d"
export COLOR0="#2d2d2d"  # black
export COLOR1="#d59192"  # red
export COLOR2="#97b393"  # green
export COLOR3="#bfb68e"  # yellow
export COLOR4="#a1a5be"  # blue
export COLOR5="#b99bb3"  # magenta
export COLOR6="#a1b0be"  # cyan
export COLOR7="#AEAEAE"  # white
export COLOR8="#4d4d4d"  # bright black
export COLOR9="#d59192"   # bright red
export COLOR10="#97b393"  # bright green
export COLOR11="#bfb68e" # bright yellow
export COLOR12="#a1a5be" # bright blue
export COLOR13="#b99bb3" # bright magenta
export COLOR14="#a1b0be" # bright cyan
export COLOR15="#cccccc"  # bright white
export COLOR_TAB_BG="#141414"
export COLOR_TAB_ACTIVE_BG="#1a1a1a"
export COLOR_TAB_ACTIVE_FG="#AEAEAE"
export COLOR_TAB_INACTIVE_FG="#636363"

_generate_wezterm_colors() {
    cat > "$HOME/colors.lua" << EOF
return {
    COLOR_FG           = "$COLOR_FG",
    COLOR_BG           = "$COLOR_BG",
    COLOR_CURSOR       = "$COLOR_CURSOR",
    COLOR_SELECTION_FG = "$COLOR_SELECTION_FG",
    COLOR_SELECTION_BG = "$COLOR_SELECTION_BG",
    COLOR0  = "$COLOR0",  COLOR1  = "$COLOR1",
    COLOR2  = "$COLOR2",  COLOR3  = "$COLOR3",
    COLOR4  = "$COLOR4",  COLOR5  = "$COLOR5",
    COLOR6  = "$COLOR6",  COLOR7  = "$COLOR7",
    COLOR8  = "$COLOR8",  COLOR9  = "$COLOR9",
    COLOR10 = "$COLOR10", COLOR11 = "$COLOR11",
    COLOR12 = "$COLOR12", COLOR13 = "$COLOR13",
    COLOR14 = "$COLOR14", COLOR15 = "$COLOR15",
    COLOR_TAB_BG          = "$COLOR_TAB_BG",
    COLOR_TAB_ACTIVE_BG   = "$COLOR_TAB_ACTIVE_BG",
    COLOR_TAB_ACTIVE_FG   = "$COLOR_TAB_ACTIVE_FG",
    COLOR_TAB_INACTIVE_FG = "$COLOR_TAB_INACTIVE_FG",
}
EOF
}

_generate_ghostty_config() {
    cat > "$HOME/.config/ghostty/colors.inc" << EOF
# Auto-generated by switch_theme() - DO NOT EDIT
background = ${COLOR_BG}
foreground = ${COLOR_FG}
cursor-color = ${COLOR_CURSOR}
selection-background = ${COLOR_SELECTION_BG}
selection-foreground = ${COLOR_SELECTION_FG}
palette = 0=${COLOR0}
palette = 1=${COLOR1}
palette = 2=${COLOR2}
palette = 3=${COLOR3}
palette = 4=${COLOR4}
palette = 5=${COLOR5}
palette = 6=${COLOR6}
palette = 7=${COLOR7}
palette = 8=${COLOR8}
palette = 9=${COLOR9}
palette = 10=${COLOR10}
palette = 11=${COLOR11}
palette = 12=${COLOR12}
palette = 13=${COLOR13}
palette = 14=${COLOR14}
palette = 15=${COLOR15}
EOF
}

switch_theme() {
    local theme="$1"
    case "$theme" in
        mellifluous)
            COLOR_FG="#cccccc"; COLOR_BG="#141414"; COLOR_CURSOR="#cccccc"
            COLOR_SELECTION_FG="#cccccc"; COLOR_SELECTION_BG="#2d2d2d"
            COLOR0="#2d2d2d"; COLOR1="#d59192"; COLOR2="#97b393"; COLOR3="#bfb68e"
            COLOR4="#a1a5be"; COLOR5="#b99bb3"; COLOR6="#a1b0be"; COLOR7="#AEAEAE"
            COLOR8="#4d4d4d"; COLOR9="#d59192"; COLOR10="#97b393"; COLOR11="#bfb68e"
            COLOR12="#a1a5be"; COLOR13="#b99bb3"; COLOR14="#a1b0be"; COLOR15="#cccccc"
            ;;
        anysphere)
            COLOR_FG="#D8DEE9"; COLOR_BG="#141414"; COLOR_CURSOR="#D8DEE9"
            COLOR_SELECTION_FG="#D8DEE9"; COLOR_SELECTION_BG="#3a3a3a"
            COLOR0="#2A2A2A"; COLOR1="#BF616A"; COLOR2="#A3BE8C"; COLOR3="#EBCB8B"
            COLOR4="#81A1C1"; COLOR5="#B48EAD"; COLOR6="#88C0D0"; COLOR7="#CCCCCC"
            COLOR8="#505050"; COLOR9="#BF616A"; COLOR10="#a8cc7c"; COLOR11="#EBCB8B"
            COLOR12="#87c3ff"; COLOR13="#e394dc"; COLOR14="#88C0D0"; COLOR15="#E5E5E5"
            ;;
        onedark)
            COLOR_FG="#abb2bf"; COLOR_BG="#282c34"; COLOR_CURSOR="#abb2bf"
            COLOR_SELECTION_FG="#abb2bf"; COLOR_SELECTION_BG="#3e4451"
            COLOR0="#282c34"; COLOR1="#e06c75"; COLOR2="#98c379"; COLOR3="#e5c07b"
            COLOR4="#61afef"; COLOR5="#be5046"; COLOR6="#56b6c2"; COLOR7="#979eab"
            COLOR8="#393e48"; COLOR9="#d19a66"; COLOR10="#56b6c2"; COLOR11="#e5c07b"
            COLOR12="#61afef"; COLOR13="#be5046"; COLOR14="#56b6c2"; COLOR15="#abb2bf"
            ;;
        kanagawa)
            COLOR_FG="#C5C9C5"; COLOR_BG="#181616"; COLOR_CURSOR="#C8C093"
            COLOR_SELECTION_FG="#C5C9C5"; COLOR_SELECTION_BG="#223249"
            COLOR0="#0D0C0C"; COLOR1="#C4746E"; COLOR2="#8A9A7B"; COLOR3="#C4B28A"
            COLOR4="#8BA4B0"; COLOR5="#A292A3"; COLOR6="#8EA4A2"; COLOR7="#C8C093"
            COLOR8="#A6A69C"; COLOR9="#E46876"; COLOR10="#87A987"; COLOR11="#E6C384"
            COLOR12="#7FB4CA"; COLOR13="#938AA9"; COLOR14="#7AA89F"; COLOR15="#C5C9C5"
            ;;
        catppuccin)
            COLOR_FG="#cdd6f4"; COLOR_BG="#1e1e2e"; COLOR_CURSOR="#f5e0dc"
            COLOR_SELECTION_FG="#cdd6f4"; COLOR_SELECTION_BG="#313244"
            COLOR0="#45475a"; COLOR1="#f38ba8"; COLOR2="#a6e3a1"; COLOR3="#f9e2af"
            COLOR4="#89b4fa"; COLOR5="#f5c2e7"; COLOR6="#94e2d5"; COLOR7="#bac2de"
            COLOR8="#585b70"; COLOR9="#f38ba8"; COLOR10="#a6e3a1"; COLOR11="#f9e2af"
            COLOR12="#89b4fa"; COLOR13="#f5c2e7"; COLOR14="#94e2d5"; COLOR15="#a6adc8"
            ;;
        tokyonight)
            COLOR_FG="#a9b1d6"; COLOR_BG="#1a1b26"; COLOR_CURSOR="#c0caf5"
            COLOR_SELECTION_FG="#a9b1d6"; COLOR_SELECTION_BG="#24283b"
            COLOR0="#15161e"; COLOR1="#f7768e"; COLOR2="#9ece6a"; COLOR3="#e0af68"
            COLOR4="#7aa2f7"; COLOR5="#bb9af7"; COLOR6="#7dcfff"; COLOR7="#a9b1d6"
            COLOR8="#414868"; COLOR9="#f7768e"; COLOR10="#9ece6a"; COLOR11="#e0af68"
            COLOR12="#7aa2f7"; COLOR13="#bb9af7"; COLOR14="#7dcfff"; COLOR15="#c0caf5"
            ;;
        vague)
            COLOR_FG="#cdcdcd"; COLOR_BG="#141415"; COLOR_CURSOR="#cdcdcd"
            COLOR_SELECTION_FG="#cdcdcd"; COLOR_SELECTION_BG="#252530"
            COLOR0="#252530"; COLOR1="#d8647e"; COLOR2="#7fa563"; COLOR3="#f3be7c"
            COLOR4="#6e94b2"; COLOR5="#bb9dbd"; COLOR6="#b4d4cf"; COLOR7="#cdcdcd"
            COLOR8="#373730"; COLOR9="#d8647e"; COLOR10="#7fa563"; COLOR11="#f3be7c"
            COLOR12="#6e94b2"; COLOR13="#bb9dbd"; COLOR14="#b4d4cf"; COLOR15="#aeaed1"
            ;;
        *)
            echo "Unknown theme: $theme"
            echo "Available: mellifluous, anysphere, onedark, kanagawa, catppuccin, tokyonight, vague"
            return 1
            ;;
    esac

    export COLOR_FG COLOR_BG COLOR_CURSOR COLOR_SELECTION_FG COLOR_SELECTION_BG
    export COLOR0 COLOR1 COLOR2 COLOR3 COLOR4 COLOR5 COLOR6 COLOR7
    export COLOR8 COLOR9 COLOR10 COLOR11 COLOR12 COLOR13 COLOR14 COLOR15

    export THEME="$theme" NVIM_THEME="$theme" STARSHIP_THEME="$theme"

    _generate_ghostty_config
    _generate_wezterm_colors

    local zshenv="$HOME/.config/zsh/.zshenv"
    if grep -q 'export THEME=' "$zshenv" 2>/dev/null; then
        sed -i '' "s/export THEME=.*/export THEME=\"$theme\"/" "$zshenv"
    fi

}


if [[ -n "$THEME" && "$THEME" != "mellifluous" ]]; then
    switch_theme "$THEME"
elif [[ -z "$THEME" ]]; then
    THEME="mellifluous"
    export THEME
    _generate_ghostty_config
    _generate_wezterm_colors
fi
